### ISSUE TITLE
Make error on RPi3

### ISSUE THREAD

**Issue by leesoh** [jamesbarlow/icmptunnel#1]
Hey there! I'm pretty excited to try out your fancy tunnelling tool but I'm getting errors when compiling it on an RPi:
```
leesoh@raspberrypi:/opt/icmptunnel $ make
[CC] src/checksum.c
*** Error in `gcc': double free or corruption (top): 0x01d8dda8 ***
Makefile:50: recipe for target 'src/checksum.o' failed
make: *** [src/checksum.o] Aborted
```
My C-fu is... nonexistent, so if this is expected behaviour on ARM-based devices, I'll just show myself out. Thanks!

**Comment by jamesbarlow** [comment]
Hi there, this looks like a bug in gcc on RPi. This may be it:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132

Within the Makefile, can you try changing CFLAGS from "-march=native" to "-mcpu=cortex-a53 -mfpu=neon-vfpv4"?

Let me know how you get on.

**Comment by leesoh** [comment]
Worked like a charm!

**Comment by jamesbarlow** [comment]
Great!
